# Generated by Django 5.2 on 2025-05-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count_likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
