# Generated by Django 5.2 on 2025-05-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_count_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='posts_pictures/', verbose_name='Posts Picture'),
        ),
    ]
